server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    #   defaultZone: http://localhost:8761/eureka
      defaultZone: http://***REMOVED***:8761/eureka

spring:
  application:
    name: eureka_api_gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://***REMOVED***'
              - 'http://***REMOVED***:443'
              - 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            exposed-headers: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: member
        #   uri: http://localhost:8011/
          uri: http://***REMOVED***:8011/
          predicates:
            - Path=/member/**, /img/member/**
        #   filters:
        #     - RewritePath=/member/(?<word>.*), /b/$\{word}
        - id: novel
        #   uri: http://localhost:8012/
          uri: http://***REMOVED***:8012/
          predicates:
            - Path=/novel/**, /write/**, /comment/**, /img/novel/**
        - id: ai
        #   uri: http://localhost:8013/
          uri: http://***REMOVED***:8013/
          predicates:
            - Path=/ai/**
        - id: payment
        #   uri: http://localhost:8014/
          uri: http://***REMOVED***:8014/
          predicates:
            - Path=/payment/**
        - id: jukebox
        #   uri: http://localhost:8015/
          uri: http://***REMOVED***:8015/
          predicates:
            - Path=/jukebox/**
