server:
  port: 8011

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://***REMOVED***:8761/eureka

spring:
  application:
    name: service_member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://***REMOVED***:3306/novel?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ***REMOVED***
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: ***REMOVED***
      port: 6379
      password:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ***REMOVED***
            client-secret: ***REMOVED***
            redirect-uri: http://***REMOVED***:8011/login/oauth2/code/google
            scope:
              - email
              - profile

jwt:
  secret: ***REMOVED***
file:
  dir: C:\Users\SSAFY\Desktop
  img:
    profile: \static\images\defaultProfileImg.png