server:
  port: 8011

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: service_member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novel?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: nextnovel
    password: ***REMOVED***
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:

jwt:
  secret: ***REMOVED***
file:
  dir: KANG