server:
  port: 8011

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://***REMOVED***:8761/eureka

spring:
  application:
    name: service_member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/members?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: nextnovel
#    password: ***REMOVED***
    url: jdbc:mysql://***REMOVED***:3306/members?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ***REMOVED***
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  redis:
#      host: 127.0.0.1
    host: 172.17.0.1
    port: 6379
    cluster:
      nodes:
#          - 127.0.0.1:6379
#          - 127.0.0.1:6380
#          - 127.0.0.1:6381
        - 172.17.0.1:6379
        - 172.17.0.1:6380
        - 172.17.0.1:6381
    password:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ***REMOVED***
            client-secret: ***REMOVED***
#            redirect-uri: http://localhost:8011/login/oauth2/code/google
            redirect-uri: http://***REMOVED***:8011/login/oauth2/code/google
            scope:
              - email
              - profile

jwt:
  secret: ***REMOVED***