server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    #   defaultZone: http://localhost:8761/eureka
      defaultZone: http://***REMOVED***:8761/eureka

spring:
  application:
    name: eureka_api_gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://***REMOVED***'
              - 'http://***REMOVED***:443'
              - 'http://localhost:3000'
            allow-credentials: true
            allowedHeaders: '*'
            exposed-headers: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: member
          uri: http://***REMOVED***:8011/
          predicates:
            - Path=/member/**, /img/member/**
        - id: novel
          uri: http://***REMOVED***:8012/
          predicates:
            - Path=/novel/**, /write/**, /comment/**, /img/novel/**
        - id: ai
          uri: http://***REMOVED***:8013/
          predicates:
            - Path=/ai/**
        - id: point
          uri: http://***REMOVED***:8014/
          predicates:
            - Path=/point/**
        - id: order
          uri: http://***REMOVED***:8015/
          predicates:
            - Path=/orders/**
        - id: item
          uri: http://***REMOVED***:8016/
          predicates:
            - Path=/items/**
        - id: orderItem
          uri: http://***REMOVED***:8017/
          predicates:
            - Path=/orderItem/**
